# Form implementation generated from reading ui file 'Ui_ActManager.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ActManager(object):
    def setupUi(self, ActManager):
        ActManager.setObjectName("ActManager")
        ActManager.resize(600, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ActManager)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=ActManager)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(ActManager)
        QtCore.QMetaObject.connectSlotsByName(ActManager)

    def retranslateUi(self, ActManager):
        _translate = QtCore.QCoreApplication.translate
        ActManager.setWindowTitle(_translate("ActManager", "账号管理 - 双击可选择对应账号应用"))
