# Form implementation generated from reading ui file 'Ui_AccountEdit.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AccountEdit(object):
    def setupUi(self, AccountEdit):
        AccountEdit.setObjectName("AccountEdit")
        AccountEdit.resize(242, 124)
        self.verticalLayout = QtWidgets.QVBoxLayout(AccountEdit)
        self.verticalLayout.setContentsMargins(3, 5, 3, 5)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(parent=AccountEdit)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_password = QtWidgets.QLineEdit(parent=AccountEdit)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.gridLayout.addWidget(self.lineEdit_password, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=AccountEdit)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=AccountEdit)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.lineEdit_desc = QtWidgets.QLineEdit(parent=AccountEdit)
        self.lineEdit_desc.setObjectName("lineEdit_desc")
        self.gridLayout.addWidget(self.lineEdit_desc, 2, 4, 1, 1)
        self.lineEdit_account = QtWidgets.QLineEdit(parent=AccountEdit)
        self.lineEdit_account.setObjectName("lineEdit_account")
        self.gridLayout.addWidget(self.lineEdit_account, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_btn = QtWidgets.QHBoxLayout()
        self.horizontalLayout_btn.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_btn.setObjectName("horizontalLayout_btn")
        self.radioButton_hk = QtWidgets.QRadioButton(parent=AccountEdit)
        self.radioButton_hk.setObjectName("radioButton_hk")
        self.horizontalLayout_btn.addWidget(self.radioButton_hk)
        self.radioButton_tw = QtWidgets.QRadioButton(parent=AccountEdit)
        self.radioButton_tw.setObjectName("radioButton_tw")
        self.horizontalLayout_btn.addWidget(self.radioButton_tw)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_btn.addItem(spacerItem)
        self.pushButton_save = QtWidgets.QPushButton(parent=AccountEdit)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_btn.addWidget(self.pushButton_save)
        self.verticalLayout.addLayout(self.horizontalLayout_btn)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(AccountEdit)
        QtCore.QMetaObject.connectSlotsByName(AccountEdit)
        AccountEdit.setTabOrder(self.lineEdit_account, self.lineEdit_password)
        AccountEdit.setTabOrder(self.lineEdit_password, self.lineEdit_desc)
        AccountEdit.setTabOrder(self.lineEdit_desc, self.radioButton_hk)
        AccountEdit.setTabOrder(self.radioButton_hk, self.radioButton_tw)
        AccountEdit.setTabOrder(self.radioButton_tw, self.pushButton_save)

    def retranslateUi(self, AccountEdit):
        _translate = QtCore.QCoreApplication.translate
        AccountEdit.setWindowTitle(_translate("AccountEdit", "账号"))
        self.label_3.setText(_translate("AccountEdit", "密码"))
        self.label_2.setText(_translate("AccountEdit", "账号"))
        self.label.setText(_translate("AccountEdit", "备注"))
        self.radioButton_hk.setText(_translate("AccountEdit", "香港"))
        self.radioButton_tw.setText(_translate("AccountEdit", "台湾"))
        self.pushButton_save.setText(_translate("AccountEdit", "保存"))
