# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_ActManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ActManager(object):
    def setupUi(self, ActManager):
        ActManager.setObjectName("ActManager")
        ActManager.resize(600, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ActManager)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(ActManager)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(ActManager)
        QtCore.QMetaObject.connectSlotsByName(ActManager)

    def retranslateUi(self, ActManager):
        _translate = QtCore.QCoreApplication.translate
        ActManager.setWindowTitle(_translate("ActManager", "AccountManager"))
