# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Config.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Config(object):
    def setupUi(self, Config):
        Config.setObjectName("Config")
        Config.resize(330, 150)
        Config.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Config)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_normal = QtWidgets.QGroupBox(Config)
        self.groupBox_normal.setObjectName("groupBox_normal")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_normal)
        self.gridLayout.setContentsMargins(-1, 2, -1, 2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_stopUpdate = QtWidgets.QCheckBox(self.groupBox_normal)
        self.checkBox_stopUpdate.setObjectName("checkBox_stopUpdate")
        self.gridLayout.addWidget(self.checkBox_stopUpdate, 0, 0, 1, 1)
        self.checkBox_closeStartWindow = QtWidgets.QCheckBox(self.groupBox_normal)
        self.checkBox_closeStartWindow.setObjectName("checkBox_closeStartWindow")
        self.gridLayout.addWidget(self.checkBox_closeStartWindow, 0, 1, 1, 1)
        self.checkBox_passInput = QtWidgets.QCheckBox(self.groupBox_normal)
        self.checkBox_passInput.setObjectName("checkBox_passInput")
        self.gridLayout.addWidget(self.checkBox_passInput, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_normal)
        self.groupBox_gamePath = QtWidgets.QGroupBox(Config)
        self.groupBox_gamePath.setObjectName("groupBox_gamePath")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_gamePath)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_gamePath = QtWidgets.QLineEdit(self.groupBox_gamePath)
        self.lineEdit_gamePath.setReadOnly(True)
        self.lineEdit_gamePath.setObjectName("lineEdit_gamePath")
        self.horizontalLayout.addWidget(self.lineEdit_gamePath)
        self.pushButton_gamePath = QtWidgets.QPushButton(self.groupBox_gamePath)
        self.pushButton_gamePath.setObjectName("pushButton_gamePath")
        self.horizontalLayout.addWidget(self.pushButton_gamePath)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addWidget(self.groupBox_gamePath)

        self.retranslateUi(Config)
        QtCore.QMetaObject.connectSlotsByName(Config)

    def retranslateUi(self, Config):
        _translate = QtCore.QCoreApplication.translate
        Config.setWindowTitle(_translate("Config", "设置"))
        self.groupBox_normal.setTitle(_translate("Config", "常规"))
        self.checkBox_stopUpdate.setText(_translate("Config", "阻止游戏更新"))
        self.checkBox_closeStartWindow.setText(_translate("Config", "跳过Play页面"))
        self.checkBox_passInput.setText(_translate("Config", "跳过登录界面"))
        self.groupBox_gamePath.setTitle(_translate("Config", "游戏目录"))
        self.pushButton_gamePath.setText(_translate("Config", "选择"))
