# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_DoubleCodeInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DoubleCodeInput(object):
    def setupUi(self, DoubleCodeInput):
        DoubleCodeInput.setObjectName("DoubleCodeInput")
        DoubleCodeInput.resize(300, 130)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DoubleCodeInput.sizePolicy().hasHeightForWidth())
        DoubleCodeInput.setSizePolicy(sizePolicy)
        DoubleCodeInput.setMinimumSize(QtCore.QSize(300, 130))
        DoubleCodeInput.setMaximumSize(QtCore.QSize(300, 130))
        DoubleCodeInput.setStyleSheet("\n"
"    QDialog {\n"
"     background-color: transparent;\n"
"    }\n"
"    #label_title {\n"
"     font-size: 18px;\n"
"     font-weight: 600;\n"
"     color: #333333;\n"
"    }\n"
"    .QLineEdit {\n"
"     font-size: 24px;\n"
"     font-weight: 600;\n"
"     border: 2px solid #e0e0e0;\n"
"     border-radius: 8px;\n"
"     color: #333333;\n"
"     background-color: #f9f9f9;\n"
"     max-length: 1;\n"
"    }\n"
"    .QLineEdit:focus {\n"
"     border-color: #409eff;\n"
"     background-color: #ffffff;\n"
"     outline: none;\n"
"    }")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DoubleCodeInput)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_title = QtWidgets.QLabel(DoubleCodeInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        self.label_title.setMinimumSize(QtCore.QSize(280, 38))
        self.label_title.setMaximumSize(QtCore.QSize(280, 38))
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_2.addWidget(self.label_title)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_1 = QtWidgets.QLineEdit(DoubleCodeInput)
        self.lineEdit_1.setMinimumSize(QtCore.QSize(38, 38))
        self.lineEdit_1.setMaximumSize(QtCore.QSize(38, 38))
        self.lineEdit_1.setMaxLength(1)
        self.lineEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.horizontalLayout.addWidget(self.lineEdit_1)
        self.lineEdit_2 = QtWidgets.QLineEdit(DoubleCodeInput)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(38, 38))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(38, 38))
        self.lineEdit_2.setMaxLength(1)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(DoubleCodeInput)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(38, 38))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(38, 38))
        self.lineEdit_3.setMaxLength(1)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(DoubleCodeInput)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(38, 38))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(38, 38))
        self.lineEdit_4.setMaxLength(1)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(DoubleCodeInput)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(38, 38))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(38, 38))
        self.lineEdit_5.setMaxLength(1)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(DoubleCodeInput)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(38, 38))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(38, 38))
        self.lineEdit_6.setMaxLength(1)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout.addWidget(self.lineEdit_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_out = QtWidgets.QPushButton(DoubleCodeInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_out.sizePolicy().hasHeightForWidth())
        self.pushButton_out.setSizePolicy(sizePolicy)
        self.pushButton_out.setMinimumSize(QtCore.QSize(0, 38))
        self.pushButton_out.setMaximumSize(QtCore.QSize(16777215, 38))
        self.pushButton_out.setObjectName("pushButton_out")
        self.horizontalLayout_2.addWidget(self.pushButton_out)
        self.pushButton_enter = QtWidgets.QPushButton(DoubleCodeInput)
        self.pushButton_enter.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_enter.sizePolicy().hasHeightForWidth())
        self.pushButton_enter.setSizePolicy(sizePolicy)
        self.pushButton_enter.setMinimumSize(QtCore.QSize(0, 38))
        self.pushButton_enter.setMaximumSize(QtCore.QSize(16777215, 38))
        self.pushButton_enter.setObjectName("pushButton_enter")
        self.horizontalLayout_2.addWidget(self.pushButton_enter)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(DoubleCodeInput)
        QtCore.QMetaObject.connectSlotsByName(DoubleCodeInput)

    def retranslateUi(self, DoubleCodeInput):
        _translate = QtCore.QCoreApplication.translate
        DoubleCodeInput.setWindowTitle(_translate("DoubleCodeInput", "双重验证"))
        self.label_title.setText(_translate("DoubleCodeInput", "请输入6位验证数字"))
        self.pushButton_out.setText(_translate("DoubleCodeInput", "取消"))
        self.pushButton_enter.setText(_translate("DoubleCodeInput", "确认"))
