# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_IntermediateLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IntermediateLogin(object):
    def setupUi(self, IntermediateLogin):
        IntermediateLogin.setObjectName("IntermediateLogin")
        IntermediateLogin.resize(200, 100)
        self.verticalLayout = QtWidgets.QVBoxLayout(IntermediateLogin)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_await = QtWidgets.QLabel(IntermediateLogin)
        self.label_await.setAlignment(QtCore.Qt.AlignCenter)
        self.label_await.setObjectName("label_await")
        self.verticalLayout.addWidget(self.label_await)

        self.retranslateUi(IntermediateLogin)
        QtCore.QMetaObject.connectSlotsByName(IntermediateLogin)

    def retranslateUi(self, IntermediateLogin):
        _translate = QtCore.QCoreApplication.translate
        IntermediateLogin.setWindowTitle(_translate("IntermediateLogin", "Await"))
        self.label_await.setText(_translate("IntermediateLogin", "请稍后..."))
