# Form implementation generated from reading ui file 'UI_Nav.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Nav(object):
    def setupUi(self, Nav):
        Nav.setObjectName("Nav")
        Nav.resize(400, 400)
        Nav.setMinimumSize(QtCore.QSize(400, 400))
        Nav.setMaximumSize(QtCore.QSize(400, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(Nav)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QWidget(parent=Nav)
        self.header.setObjectName("header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_search = QtWidgets.QLineEdit(parent=self.header)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout.addWidget(self.lineEdit_search)
        self.checkBox_outer = QtWidgets.QCheckBox(parent=self.header)
        self.checkBox_outer.setObjectName("checkBox_outer")
        self.horizontalLayout.addWidget(self.checkBox_outer)
        self.pushButton_refresh = QtWidgets.QPushButton(parent=self.header)
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.horizontalLayout.addWidget(self.pushButton_refresh)
        self.verticalLayout.addWidget(self.header)
        self.scrollArea = QtWidgets.QScrollArea(parent=Nav)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 392, 369))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_content = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_content.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_content.setSpacing(8)
        self.verticalLayout_content.setObjectName("verticalLayout_content")
        self.container = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.container.setObjectName("container")
        self.verticalLayout_groups = QtWidgets.QVBoxLayout(self.container)
        self.verticalLayout_groups.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_groups.setSpacing(8)
        self.verticalLayout_groups.setObjectName("verticalLayout_groups")
        self.verticalLayout_content.addWidget(self.container)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_content.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Nav)
        QtCore.QMetaObject.connectSlotsByName(Nav)

    def retranslateUi(self, Nav):
        _translate = QtCore.QCoreApplication.translate
        Nav.setWindowTitle(_translate("Nav", "便捷导航"))
        self.lineEdit_search.setPlaceholderText(_translate("Nav", "搜索..."))
        self.checkBox_outer.setText(_translate("Nav", "默认浏览器"))
        self.pushButton_refresh.setText(_translate("Nav", "刷新"))
