# Form implementation generated from reading ui file 'Ui_QrCodeLogin.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_QrCodeLogin(object):
    def setupUi(self, QrCodeLogin):
        QrCodeLogin.setObjectName("QrCodeLogin")
        QrCodeLogin.resize(300, 300)
        QrCodeLogin.setMinimumSize(QtCore.QSize(300, 300))
        QrCodeLogin.setMaximumSize(QtCore.QSize(300, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(QrCodeLogin)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_qrCode = QtWidgets.QLabel(parent=QrCodeLogin)
        self.label_qrCode.setScaledContents(True)
        self.label_qrCode.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_qrCode.setObjectName("label_qrCode")
        self.verticalLayout.addWidget(self.label_qrCode)

        self.retranslateUi(QrCodeLogin)
        QtCore.QMetaObject.connectSlotsByName(QrCodeLogin)

    def retranslateUi(self, QrCodeLogin):
        _translate = QtCore.QCoreApplication.translate
        QrCodeLogin.setWindowTitle(_translate("QrCodeLogin", "GamePass"))
