# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_QrCodeShow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QrCodeShow(object):
    def setupUi(self, QrCodeShow):
        QrCodeShow.setObjectName("QrCodeShow")
        QrCodeShow.resize(400, 400)
        QrCodeShow.setMinimumSize(QtCore.QSize(400, 400))
        QrCodeShow.setMaximumSize(QtCore.QSize(400, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(QrCodeShow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_qrCode = QtWidgets.QLabel(QrCodeShow)
        self.label_qrCode.setScaledContents(True)
        self.label_qrCode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_qrCode.setObjectName("label_qrCode")
        self.verticalLayout.addWidget(self.label_qrCode)

        self.retranslateUi(QrCodeShow)
        QtCore.QMetaObject.connectSlotsByName(QrCodeShow)

    def retranslateUi(self, QrCodeShow):
        pass
