# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_QrCodeLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QrCodeLogin(object):
    def setupUi(self, QrCodeLogin):
        QrCodeLogin.setObjectName("QrCodeLogin")
        QrCodeLogin.resize(200, 200)
        QrCodeLogin.setMinimumSize(QtCore.QSize(200, 200))
        QrCodeLogin.setMaximumSize(QtCore.QSize(200, 200))
        self.verticalLayout = QtWidgets.QVBoxLayout(QrCodeLogin)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_qrCode = QtWidgets.QLabel(QrCodeLogin)
        self.label_qrCode.setScaledContents(True)
        self.label_qrCode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_qrCode.setObjectName("label_qrCode")
        self.verticalLayout.addWidget(self.label_qrCode)

        self.retranslateUi(QrCodeLogin)
        QtCore.QMetaObject.connectSlotsByName(QrCodeLogin)

    def retranslateUi(self, QrCodeLogin):
        _translate = QtCore.QCoreApplication.translate
        QrCodeLogin.setWindowTitle(_translate("QrCodeLogin", "二維碼登入"))
