# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_TwAdv.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TwAdv(object):
    def setupUi(self, TwAdv):
        TwAdv.setObjectName("TwAdv")
        TwAdv.resize(210, 200)
        TwAdv.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(TwAdv)
        self.verticalLayout.setContentsMargins(5, 3, 5, 3)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_verifyCode = QtWidgets.QLabel(TwAdv)
        self.label_verifyCode.setMinimumSize(QtCore.QSize(200, 45))
        self.label_verifyCode.setMaximumSize(QtCore.QSize(200, 45))
        self.label_verifyCode.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_verifyCode.setStyleSheet("padding:0px;border:0px;")
        self.label_verifyCode.setText("")
        self.label_verifyCode.setScaledContents(True)
        self.label_verifyCode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_verifyCode.setObjectName("label_verifyCode")
        self.verticalLayout.addWidget(self.label_verifyCode)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(TwAdv)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_phone = QtWidgets.QLineEdit(TwAdv)
        self.lineEdit_phone.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_phone.setFont(font)
        self.lineEdit_phone.setMaxLength(33)
        self.lineEdit_phone.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.gridLayout.addWidget(self.lineEdit_phone, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(TwAdv)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_verifyCode = QtWidgets.QLineEdit(TwAdv)
        self.lineEdit_verifyCode.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_verifyCode.setFont(font)
        self.lineEdit_verifyCode.setMaxLength(18)
        self.lineEdit_verifyCode.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_verifyCode.setObjectName("lineEdit_verifyCode")
        self.gridLayout.addWidget(self.lineEdit_verifyCode, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(TwAdv)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_tips = QtWidgets.QLabel(TwAdv)
        self.label_tips.setMaximumSize(QtCore.QSize(16777215, 17))
        self.label_tips.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tips.setObjectName("label_tips")
        self.gridLayout.addWidget(self.label_tips, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.pushButton_send = QtWidgets.QPushButton(TwAdv)
        self.pushButton_send.setMinimumSize(QtCore.QSize(0, 42))
        self.pushButton_send.setObjectName("pushButton_send")
        self.verticalLayout.addWidget(self.pushButton_send)

        self.retranslateUi(TwAdv)
        QtCore.QMetaObject.connectSlotsByName(TwAdv)
        TwAdv.setTabOrder(self.lineEdit_verifyCode, self.lineEdit_phone)
        TwAdv.setTabOrder(self.lineEdit_phone, self.pushButton_send)

    def retranslateUi(self, TwAdv):
        _translate = QtCore.QCoreApplication.translate
        TwAdv.setWindowTitle(_translate("TwAdv", "登入驗證"))
        self.label_3.setText(_translate("TwAdv", "圖形驗證碼"))
        self.label_5.setText(_translate("TwAdv", "提示資料"))
        self.label_4.setText(_translate("TwAdv", "手提號碼"))
        self.label_tips.setText(_translate("TwAdv", "XXXXXXXXXXXX"))
        self.pushButton_send.setText(_translate("TwAdv", "確認送出"))
